"""
NVIDIA NeMo Data Designer - Synthetic Data Generation.

Provides:
- Generate synthetic stress test scenarios
- Create cascade failure examples
- Generate training data for rare events
- Augment historical data with variations
"""
import logging
from dataclasses import dataclass
from typing import Any, Dict, List, Optional

import httpx

from src.core.config import settings

logger = logging.getLogger(__name__)


@dataclass
class SyntheticScenario:
    """Synthetic scenario generated by Data Designer."""
    scenario_id: str
    name: str
    scenario_type: str  # flood, earthquake, drought, etc.
    severity: float  # 0.0-1.0
    region: str
    parameters: Dict[str, Any]
    generated_at: str


@dataclass
class GenerationResult:
    """Result of synthetic data generation."""
    scenarios_generated: int
    scenarios: List[SyntheticScenario]
    generation_time_ms: float
    model_used: str


class NeMoDataDesignerService:
    """
    NeMo Data Designer Service for synthetic data generation.
    
    Generates:
    - Stress test scenarios
    - Cascade failure examples
    - Rare event training data
    - Historical data variations
    """
    
    def __init__(self):
        self.enabled = getattr(settings, 'nemo_data_designer_enabled', True)
        self.model = getattr(settings, 'data_designer_model', 'nemotron-4')
        self.temperature = getattr(settings, 'data_designer_temperature', 0.7)
        
        # API endpoint (if using NVIDIA Cloud API)
        self.nvidia_api_key = getattr(settings, 'nvidia_api_key', '') or ''
        self.api_url = "https://integrate.api.nvidia.com/v1/chat/completions"
        
        self.http_client = httpx.AsyncClient(
            timeout=60.0,
            headers={
                'Authorization': f'Bearer {self.nvidia_api_key}',
                'Content-Type': 'application/json'
            } if self.nvidia_api_key else {}
        )
    
    async def generate_stress_test_scenarios(
        self,
        scenario_type: str,
        region: str,
        count: int = 10,
        severity_range: tuple = (0.5, 1.0),
        **parameters,
    ) -> GenerationResult:
        """
        Generate synthetic stress test scenarios.
        
        Args:
            scenario_type: Type of scenario (flood, earthquake, drought, etc.)
            region: Geographic region
            count: Number of scenarios to generate
            severity_range: Tuple of (min, max) severity
            **parameters: Additional parameters for generation
            
        Returns:
            GenerationResult with generated scenarios
        """
        import time
        from datetime import datetime
        from uuid import uuid4
        
        start_time = time.time()
        
        if not self.enabled:
            # Return empty result if disabled
            return GenerationResult(
                scenarios_generated=0,
                scenarios=[],
                generation_time_ms=0.0,
                model_used="disabled",
            )
        
        scenarios = []
        
        # Generate scenarios
        for i in range(count):
            try:
                scenario = await self._generate_single_scenario(
                    scenario_type=scenario_type,
                    region=region,
                    severity_range=severity_range,
                    index=i,
                    **parameters,
                )
                scenarios.append(scenario)
            except Exception as e:
                logger.warning(f"Failed to generate scenario {i}: {e}")
                continue
        
        generation_time = (time.time() - start_time) * 1000
        
        return GenerationResult(
            scenarios_generated=len(scenarios),
            scenarios=scenarios,
            generation_time_ms=generation_time,
            model_used=self.model,
        )
    
    async def _generate_single_scenario(
        self,
        scenario_type: str,
        region: str,
        severity_range: tuple,
        index: int,
        **parameters,
    ) -> SyntheticScenario:
        """Generate a single synthetic scenario."""
        from datetime import datetime
        from uuid import uuid4
        import random
        
        # If NVIDIA API is available, use it for more realistic generation
        if self.nvidia_api_key:
            try:
                scenario = await self._generate_with_llm(
                    scenario_type=scenario_type,
                    region=region,
                    severity_range=severity_range,
                    **parameters,
                )
                return scenario
            except Exception as e:
                logger.debug(f"LLM generation failed, using template: {e}")
        
        # Fallback: Template-based generation
        severity = random.uniform(severity_range[0], severity_range[1])
        
        # Template parameters based on scenario type
        templates = {
            "flood": {
                "name": f"{region} Flood Scenario {index + 1}",
                "water_level_m": round(random.uniform(1.0, 5.0), 2),
                "duration_days": random.randint(3, 14),
                "affected_area_km2": round(random.uniform(10, 500), 2),
            },
            "earthquake": {
                "name": f"{region} Earthquake Scenario {index + 1}",
                "magnitude": round(random.uniform(5.0, 8.5), 1),
                "depth_km": random.randint(5, 50),
                "affected_area_km2": round(random.uniform(50, 1000), 2),
            },
            "drought": {
                "name": f"{region} Drought Scenario {index + 1}",
                "precipitation_deficit_pct": round(random.uniform(30, 70), 1),
                "duration_months": random.randint(6, 36),
                "temperature_increase_c": round(random.uniform(2.0, 5.0), 1),
            },
            "hurricane": {
                "name": f"{region} Hurricane Scenario {index + 1}",
                "category": random.randint(1, 5),
                "wind_speed_kmh": random.randint(120, 250),
                "affected_area_km2": round(random.uniform(100, 2000), 2),
            },
        }
        
        template = templates.get(scenario_type.lower(), {
            "name": f"{region} {scenario_type} Scenario {index + 1}",
        })
        
        # Merge with provided parameters
        scenario_params = {**template, **parameters}
        
        return SyntheticScenario(
            scenario_id=str(uuid4()),
            name=scenario_params.get("name", f"{scenario_type} Scenario {index + 1}"),
            scenario_type=scenario_type,
            severity=severity,
            region=region,
            parameters=scenario_params,
            generated_at=datetime.utcnow().isoformat(),
        )
    
    async def _generate_with_llm(
        self,
        scenario_type: str,
        region: str,
        severity_range: tuple,
        **parameters,
    ) -> SyntheticScenario:
        """Generate scenario using NVIDIA LLM."""
        from datetime import datetime
        from uuid import uuid4
        import json
        
        prompt = f"""Generate a realistic {scenario_type} stress test scenario for {region}.

Requirements:
- Severity: {severity_range[0]:.2f} to {severity_range[1]:.2f}
- Region: {region}
- Type: {scenario_type}

Return JSON with:
{{
    "name": "Scenario name",
    "severity": 0.0-1.0,
    "parameters": {{
        "key": "value"
    }}
}}
"""
        
        try:
            response = await self.http_client.post(
                self.api_url,
                json={
                    "model": self.model,
                    "messages": [
                        {"role": "system", "content": "You are a risk scenario generator. Return only valid JSON."},
                        {"role": "user", "content": prompt}
                    ],
                    "temperature": self.temperature,
                    "max_tokens": 500,
                }
            )
            
            if response.status_code == 200:
                data = response.json()
                content = data.get("choices", [{}])[0].get("message", {}).get("content", "{}")
                
                # Parse JSON from response
                try:
                    scenario_data = json.loads(content)
                except json.JSONDecodeError:
                    # Try to extract JSON from markdown code blocks
                    import re
                    json_match = re.search(r'```json\s*(.*?)\s*```', content, re.DOTALL)
                    if json_match:
                        scenario_data = json.loads(json_match.group(1))
                    else:
                        raise ValueError("Could not parse JSON from LLM response")
                
                return SyntheticScenario(
                    scenario_id=str(uuid4()),
                    name=scenario_data.get("name", f"{scenario_type} Scenario"),
                    scenario_type=scenario_type,
                    severity=scenario_data.get("severity", 0.7),
                    region=region,
                    parameters=scenario_data.get("parameters", {}),
                    generated_at=datetime.utcnow().isoformat(),
                )
            else:
                raise ValueError(f"LLM API returned {response.status_code}")
        except Exception as e:
            logger.warning(f"LLM generation failed: {e}")
            raise
    
    async def generate_cascade_examples(
        self,
        trigger_type: str,
        depth: int = 3,
        count: int = 5,
    ) -> List[Dict[str, Any]]:
        """
        Generate cascade failure examples.
        
        Args:
            trigger_type: Type of trigger (power_grid_failure, flood, etc.)
            depth: Depth of cascade (number of levels)
            count: Number of examples to generate
            
        Returns:
            List of cascade examples
        """
        import random
        from uuid import uuid4
        
        examples = []
        
        for i in range(count):
            cascade = {
                "id": str(uuid4()),
                "trigger_type": trigger_type,
                "depth": depth,
                "levels": [],
            }
            
            # Generate cascade levels
            for level in range(depth):
                affected_count = random.randint(2, 10) * (level + 1)
                cascade["levels"].append({
                    "level": level + 1,
                    "affected_nodes": affected_count,
                    "impact_multiplier": 1.0 + (level * 0.3),
                    "time_delay_hours": level * 6,
                })
            
            examples.append(cascade)
        
        return examples
    
    async def augment_historical_data(
        self,
        base_event: Dict[str, Any],
        variations: int = 5,
        variation_range: float = 0.2,
    ) -> List[Dict[str, Any]]:
        """
        Augment historical event with variations.
        
        Args:
            base_event: Base historical event
            variations: Number of variations to generate
            variation_range: Range of variation (0.2 = ±20%)
            
        Returns:
            List of augmented events
        """
        import random
        from uuid import uuid4
        from datetime import datetime, timedelta
        
        augmented = []
        
        for i in range(variations):
            variation = base_event.copy()
            variation["id"] = str(uuid4())
            variation["name"] = f"{base_event.get('name', 'Event')} (Variation {i + 1})"
            
            # Vary severity
            if "severity_actual" in variation:
                base_severity = variation["severity_actual"] or 0.5
                variation["severity_actual"] = max(0.0, min(1.0, 
                    base_severity + random.uniform(-variation_range, variation_range)
                ))
            
            # Vary financial loss
            if "financial_loss_eur" in variation and variation["financial_loss_eur"]:
                base_loss = variation["financial_loss_eur"]
                variation["financial_loss_eur"] = max(0, 
                    base_loss * (1 + random.uniform(-variation_range, variation_range))
                )
            
            # Vary date (within ±1 year)
            if "start_date" in variation and variation["start_date"]:
                try:
                    if isinstance(variation["start_date"], str):
                        base_date = datetime.fromisoformat(variation["start_date"])
                    else:
                        base_date = variation["start_date"]
                    
                    days_offset = random.randint(-365, 365)
                    variation["start_date"] = (base_date + timedelta(days=days_offset)).isoformat()
                except (ValueError, TypeError):
                    pass
            
            augmented.append(variation)
        
        return augmented


# Global service instance
_nemo_data_designer_service: Optional[NeMoDataDesignerService] = None


def get_nemo_data_designer_service() -> NeMoDataDesignerService:
    """Get or create NeMo Data Designer service instance."""
    global _nemo_data_designer_service
    if _nemo_data_designer_service is None:
        _nemo_data_designer_service = NeMoDataDesignerService()
    return _nemo_data_designer_service


# Convenience alias
nemo_data_designer = get_nemo_data_designer_service()
