"""
Developer ecosystem endpoints: webhooks, Agent OS workflows, model registry.
"""
import json
import secrets
from datetime import datetime
from typing import Any, Dict, List, Optional
from uuid import uuid4

from fastapi import APIRouter, Depends, HTTPException, Query
from pydantic import BaseModel, Field
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from src.core.database import get_db
from src.core.security import get_current_active_user
from src.models.user import User
from src.models.webhook import Webhook
from src.services.agent_os import workflow_executor
from src.services.approval_gate import approval_gate

router = APIRouter()


# ========================== Webhooks ==========================

class WebhookCreate(BaseModel):
    name: str = Field(..., min_length=1, max_length=100)
    url: str = Field(..., min_length=10)
    events: List[str] = Field(default_factory=lambda: ["alert.created", "stress_test.completed"])


class WebhookResponse(BaseModel):
    id: str
    name: str
    url: str
    events: List[str]
    is_active: bool
    secret: Optional[str] = None
    created_at: Optional[str] = None


@router.post("/webhooks", response_model=WebhookResponse)
async def create_webhook(
    body: WebhookCreate,
    user: User = Depends(get_current_active_user),
    db: AsyncSession = Depends(get_db),
):
    """Create a webhook subscription."""
    secret = secrets.token_urlsafe(32)
    wh = Webhook(
        id=str(uuid4()),
        user_id=user.id,
        name=body.name,
        url=body.url,
        secret=secret,
        events=json.dumps(body.events),
    )
    db.add(wh)
    await db.commit()
    return WebhookResponse(
        id=wh.id, name=wh.name, url=wh.url,
        events=body.events, is_active=True, secret=secret,
        created_at=wh.created_at.isoformat() if wh.created_at else None,
    )


@router.get("/webhooks")
async def list_webhooks(
    user: User = Depends(get_current_active_user),
    db: AsyncSession = Depends(get_db),
):
    """List webhooks for current user."""
    result = await db.execute(
        select(Webhook).where(Webhook.user_id == user.id).order_by(Webhook.created_at.desc())
    )
    hooks = result.scalars().all()
    return [
        {
            "id": h.id, "name": h.name, "url": h.url,
            "events": json.loads(h.events) if h.events else [],
            "is_active": h.is_active,
            "failure_count": h.failure_count,
            "last_triggered_at": h.last_triggered_at.isoformat() if h.last_triggered_at else None,
        }
        for h in hooks
    ]


@router.delete("/webhooks/{webhook_id}")
async def delete_webhook(
    webhook_id: str,
    user: User = Depends(get_current_active_user),
    db: AsyncSession = Depends(get_db),
):
    """Delete a webhook."""
    result = await db.execute(
        select(Webhook).where(Webhook.id == webhook_id, Webhook.user_id == user.id)
    )
    wh = result.scalar_one_or_none()
    if not wh:
        raise HTTPException(status_code=404, detail="Webhook not found")
    await db.delete(wh)
    await db.commit()
    return {"status": "deleted", "id": webhook_id}


@router.get("/webhook-events")
async def list_webhook_events():
    """List available webhook event types."""
    return {
        "events": [
            {"type": "alert.created", "description": "New alert generated by SENTINEL"},
            {"type": "alert.resolved", "description": "Alert resolved"},
            {"type": "stress_test.completed", "description": "Stress test run completed"},
            {"type": "stress_test.failed", "description": "Stress test run failed"},
            {"type": "agent.recommendation", "description": "Agent generated a recommendation"},
            {"type": "asset.created", "description": "New asset created"},
            {"type": "asset.risk_changed", "description": "Asset risk score changed significantly"},
            {"type": "report.generated", "description": "Report generated"},
            {"type": "workflow.completed", "description": "Agent workflow completed"},
        ]
    }


# ========================== Agent OS Workflows ==========================

@router.get("/workflows/templates")
async def list_workflow_templates():
    """List available Agent OS workflow templates."""
    return {"templates": workflow_executor.list_templates()}


@router.get("/workflows/templates/{template_id}")
async def get_workflow_template(template_id: str):
    """Get a workflow template definition."""
    t = workflow_executor.get_template(template_id)
    if not t:
        raise HTTPException(status_code=404, detail="Template not found")
    return {
        "id": t.id, "name": t.name, "description": t.description,
        "version": t.version, "tags": t.tags,
        "steps": [
            {"id": s.id, "name": s.name, "agent": s.agent, "action": s.action,
             "depends_on": s.depends_on, "params": s.params}
            for s in t.steps
        ],
    }


class StartWorkflowRequest(BaseModel):
    template_id: str
    context: Optional[Dict[str, Any]] = None


@router.post("/workflows/run")
async def start_workflow(
    body: StartWorkflowRequest,
):
    """Start executing an Agent OS workflow."""
    try:
        run = await workflow_executor.start_workflow(body.template_id, body.context)
    except ValueError as e:
        raise HTTPException(status_code=404, detail=str(e))
    return {
        "run_id": run.id,
        "template_id": run.template_id,
        "status": run.status,
        "steps_completed": run.steps_completed,
        "steps_failed": run.steps_failed,
        "results": run.results,
        "duration_seconds": round((run.completed_at or 0) - run.started_at, 2),
    }


@router.get("/workflows/runs")
async def list_workflow_runs(limit: int = Query(50, ge=1, le=200)):
    """List recent workflow runs."""
    return {"runs": workflow_executor.list_runs(limit=limit)}


@router.get("/workflows/runs/{run_id}")
async def get_workflow_run(run_id: str):
    """Get a workflow run status."""
    run = workflow_executor.get_run(run_id)
    if not run:
        raise HTTPException(status_code=404, detail="Workflow run not found")
    return {
        "id": run.id, "template_id": run.template_id, "status": run.status,
        "steps_completed": run.steps_completed, "steps_failed": run.steps_failed,
        "context": run.context, "results": run.results,
        "started_at": run.started_at, "completed_at": run.completed_at,
    }


# ========================== HITL Approvals ==========================

@router.get("/workflows/approvals/pending")
async def list_pending_approvals(
    workflow_run_id: Optional[str] = Query(None, description="Filter by workflow run ID"),
):
    """List pending human-in-the-loop approval requests."""
    pending = approval_gate.list_pending(workflow_run_id=workflow_run_id)
    return {"pending": pending}


class DecideApprovalRequest(BaseModel):
    decision: str = Field(..., description="approved | rejected | modified")
    reason: str = Field("", description="Optional reason for the decision")
    modifications: Optional[Dict[str, Any]] = Field(None, description="Optional payload modifications when decision=modified")
    decided_by: str = Field("human", description="Identifier of the decider")


@router.post("/workflows/approvals/{gate_id}/decide")
async def decide_approval(gate_id: str, body: DecideApprovalRequest):
    """Approve, reject, or modify a pending approval gate."""
    if body.decision not in ("approved", "rejected", "modified"):
        raise HTTPException(status_code=400, detail="decision must be approved, rejected, or modified")
    ok = await approval_gate.decide(
        gate_id,
        decision=body.decision,
        decided_by=body.decided_by,
        reason=body.reason,
        modifications=body.modifications,
    )
    if not ok:
        raise HTTPException(status_code=404, detail="Approval gate not found")
    return {"status": "ok", "gate_id": gate_id}
