"""
SENTINEL Agent - 24/7 Monitoring and Alert Generation.

Responsibilities:
- Monitor weather forecasts for threats
- Detect anomalies in sensor data
- Track infrastructure status
- Generate alerts when thresholds exceeded
"""
import logging
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Optional
from uuid import UUID, uuid4

logger = logging.getLogger(__name__)


class AlertSeverity(str, Enum):
    """Alert severity levels."""
    INFO = "info"
    WARNING = "warning"
    HIGH = "high"
    CRITICAL = "critical"


class AlertType(str, Enum):
    """Types of alerts."""
    WEATHER_THREAT = "weather_threat"
    SENSOR_ANOMALY = "sensor_anomaly"
    INFRASTRUCTURE_ISSUE = "infrastructure_issue"
    CLIMATE_THRESHOLD = "climate_threshold"
    FINANCIAL_THRESHOLD = "financial_threshold"
    MAINTENANCE_DUE = "maintenance_due"
    CASCADE_RISK = "cascade_risk"


@dataclass
class Alert:
    """Alert generated by Sentinel."""
    id: UUID
    alert_type: AlertType
    severity: AlertSeverity
    title: str
    message: str
    asset_ids: list[str]
    exposure: float
    recommended_actions: list[str]
    created_at: datetime
    expires_at: Optional[datetime] = None
    acknowledged: bool = False
    resolved: bool = False


class SentinelAgent:
    """
    SENTINEL Agent - Always watching.
    
    Monitors:
    - Weather forecasts (storms, floods, heat waves)
    - Sensor data streams
    - Infrastructure status
    - Climate risk thresholds
    - Financial triggers
    """
    
    def __init__(self):
        self.rules: list[dict] = []
        self.active_alerts: dict[UUID, Alert] = {}
        self._load_default_rules()
    
    def _load_default_rules(self):
        """Load default monitoring rules."""
        self.rules = [
            {
                "id": "weather_hurricane",
                "name": "Hurricane Threat",
                "condition": "weather_forecast.hurricane AND affected_region INTERSECTS portfolio",
                "severity": AlertSeverity.CRITICAL,
                "lookback_hours": 72,
            },
            {
                "id": "weather_flood",
                "name": "Flood Warning",
                "condition": "weather_forecast.flood_warning AND asset.flood_score > 50",
                "severity": AlertSeverity.HIGH,
                "lookback_hours": 24,
            },
            {
                "id": "climate_threshold",
                "name": "Climate Risk Threshold",
                "condition": "asset.climate_risk_score > 70",
                "severity": AlertSeverity.WARNING,
            },
            {
                "id": "sensor_structural",
                "name": "Structural Anomaly",
                "condition": "sensor.structural_integrity.change > 5%",
                "severity": AlertSeverity.HIGH,
            },
            {
                "id": "infrastructure_power",
                "name": "Power Grid Issue",
                "condition": "infrastructure.power.status != 'normal'",
                "severity": AlertSeverity.HIGH,
            },
            {
                "id": "maintenance_due",
                "name": "Maintenance Due",
                "condition": "asset.last_inspection_days > 365",
                "severity": AlertSeverity.INFO,
            },
        ]
    
    async def monitor(self, context: dict) -> list[Alert]:
        """
        Run monitoring cycle and generate alerts.
        
        Args:
            context: Current state including:
                - weather_forecast: Current weather data
                - assets: Asset states
                - sensors: Latest sensor readings
                - infrastructure: Infrastructure status
                
        Returns:
            List of generated alerts
        """
        alerts = []
        
        # Check weather threats
        weather_alerts = await self._check_weather_threats(context.get("weather_forecast", {}))
        alerts.extend(weather_alerts)
        
        # Check sensor anomalies
        sensor_alerts = await self._check_sensor_anomalies(context.get("sensors", {}))
        alerts.extend(sensor_alerts)
        
        # Check infrastructure status
        infra_alerts = await self._check_infrastructure(context.get("infrastructure", {}))
        alerts.extend(infra_alerts)
        
        # Check climate thresholds
        climate_alerts = await self._check_climate_thresholds(context.get("assets", []))
        alerts.extend(climate_alerts)
        
        # Store active alerts
        for alert in alerts:
            self.active_alerts[alert.id] = alert
        
        return alerts
    
    async def _check_weather_threats(self, weather: dict) -> list[Alert]:
        """Check for weather-related threats."""
        alerts = []
        
        # Hurricane detection (simulated)
        if weather.get("hurricane"):
            hurricane = weather["hurricane"]
            alert = Alert(
                id=uuid4(),
                alert_type=AlertType.WEATHER_THREAT,
                severity=AlertSeverity.CRITICAL,
                title=f"Hurricane {hurricane.get('name', 'Unknown')} Approaching",
                message=f"Category {hurricane.get('category', 3)} hurricane forecast for "
                        f"{hurricane.get('region', 'affected area')} in {hurricane.get('hours', 72)} hours. "
                        f"Estimated exposure: €{hurricane.get('exposure', 0):,.0f}M",
                asset_ids=hurricane.get("affected_assets", []),
                exposure=hurricane.get("exposure", 0) * 1_000_000,
                recommended_actions=[
                    "Activate emergency protocols",
                    "Verify insurance coverage",
                    "Pre-stage repair crews",
                    "Notify tenants",
                ],
                created_at=datetime.utcnow(),
            )
            alerts.append(alert)
        
        # Flood warning
        if weather.get("flood_warning"):
            flood = weather["flood_warning"]
            alert = Alert(
                id=uuid4(),
                alert_type=AlertType.WEATHER_THREAT,
                severity=AlertSeverity.HIGH,
                title="Flood Warning Active",
                message=f"Flood warning for {flood.get('region', 'region')}. "
                        f"Expected water level: {flood.get('level', 0)}m",
                asset_ids=flood.get("affected_assets", []),
                exposure=flood.get("exposure", 0),
                recommended_actions=[
                    "Move valuables to higher floors",
                    "Check flood barriers",
                    "Review evacuation routes",
                ],
                created_at=datetime.utcnow(),
            )
            alerts.append(alert)
        
        return alerts
    
    async def _check_sensor_anomalies(self, sensors: dict) -> list[Alert]:
        """Check for anomalies in sensor data."""
        alerts = []
        
        for asset_id, readings in sensors.items():
            # Structural integrity drop
            if readings.get("structural_integrity_change", 0) > 5:
                alert = Alert(
                    id=uuid4(),
                    alert_type=AlertType.SENSOR_ANOMALY,
                    severity=AlertSeverity.HIGH,
                    title=f"Structural Anomaly Detected",
                    message=f"Structural integrity dropped by "
                            f"{readings.get('structural_integrity_change', 0):.1f}% in the last 24 hours.",
                    asset_ids=[asset_id],
                    exposure=0,  # To be calculated
                    recommended_actions=[
                        "Schedule immediate inspection",
                        "Review structural history",
                        "Consider temporary restrictions",
                    ],
                    created_at=datetime.utcnow(),
                )
                alerts.append(alert)
        
        return alerts
    
    async def _check_infrastructure(self, infrastructure: dict) -> list[Alert]:
        """Check infrastructure status."""
        alerts = []
        
        for infra_id, status in infrastructure.items():
            if status.get("status") != "normal":
                alert = Alert(
                    id=uuid4(),
                    alert_type=AlertType.INFRASTRUCTURE_ISSUE,
                    severity=AlertSeverity.HIGH if status.get("status") == "critical" else AlertSeverity.WARNING,
                    title=f"Infrastructure Issue: {infra_id}",
                    message=f"{status.get('type', 'Infrastructure')} status: {status.get('status')}. "
                            f"Affected assets: {status.get('affected_count', 0)}",
                    asset_ids=status.get("affected_assets", []),
                    exposure=status.get("exposure", 0),
                    recommended_actions=[
                        "Contact infrastructure operator",
                        "Activate backup systems",
                        "Monitor cascade effects",
                    ],
                    created_at=datetime.utcnow(),
                )
                alerts.append(alert)
        
        return alerts
    
    async def _check_climate_thresholds(self, assets: list[dict]) -> list[Alert]:
        """Check climate risk thresholds."""
        alerts = []
        
        high_risk_assets = [a for a in assets if a.get("climate_risk_score", 0) > 70]
        
        if high_risk_assets:
            alert = Alert(
                id=uuid4(),
                alert_type=AlertType.CLIMATE_THRESHOLD,
                severity=AlertSeverity.WARNING,
                title=f"{len(high_risk_assets)} Assets Exceed Climate Risk Threshold",
                message=f"{len(high_risk_assets)} assets have climate risk scores above 70. "
                        f"Review and consider mitigation strategies.",
                asset_ids=[a.get("id", "") for a in high_risk_assets],
                exposure=sum(a.get("valuation", 0) for a in high_risk_assets),
                recommended_actions=[
                    "Run detailed climate stress test",
                    "Evaluate physical adaptation measures",
                    "Review insurance coverage",
                    "Consider portfolio rebalancing",
                ],
                created_at=datetime.utcnow(),
            )
            alerts.append(alert)
        
        return alerts
    
    def get_active_alerts(self, severity: Optional[AlertSeverity] = None) -> list[Alert]:
        """Get all active (unresolved) alerts."""
        alerts = [a for a in self.active_alerts.values() if not a.resolved]
        
        if severity:
            alerts = [a for a in alerts if a.severity == severity]
        
        return sorted(alerts, key=lambda a: (
            {"critical": 0, "high": 1, "warning": 2, "info": 3}[a.severity.value],
            a.created_at
        ))
    
    def acknowledge_alert(self, alert_id: UUID) -> bool:
        """Acknowledge an alert."""
        if alert_id in self.active_alerts:
            self.active_alerts[alert_id].acknowledged = True
            return True
        return False
    
    def resolve_alert(self, alert_id: UUID) -> bool:
        """Resolve an alert."""
        if alert_id in self.active_alerts:
            self.active_alerts[alert_id].resolved = True
            return True
        return False


# Global agent instance
sentinel_agent = SentinelAgent()
